### PR TITLE
Add support to build example using travis-ci

### PR DESCRIPTION
**Pull request by sieben**
I think it would be a good idea to include in the travis-ci all the required steps to build the guide. I can't find the docs to build the guide easily...

Also you need to activate travis-ci hook for this repo. It's free :-)

### CODE REVIEW

**Comment by sieben** [comment]
@pieter did you also activate the hook in the admin interface?

I can't find the build showing up at :
https://travis-ci.org/booksbyus/zguide

Also right now, this code only test examples builds. How can I build the
guide. I can't find the documentation for it...

Le jeu. 8 sept. 2016 02:22, Pieter Hintjens <notifications@github.com> a
écrit :

**Comment by hintjens** [comment]
Hmm, I'm inviting you to the admin team so you can do this. :-)

**Comment by sieben** [comment]
No problem :-) Glad to help. Normally an access request pending is on its
way. Tell me when you receive and activate it. :)

Le jeu. 8 sept. 2016 à 09:35, Pieter Hintjens <notifications@github.com> a
écrit :

**Comment by hintjens** [comment]
Should work now, you should have admin access to the repo.

**Comment by sieben** [comment]
Indeed you can see it live here :

https://travis-ci.org/booksbyus/zguide

As you can see there is multiples errors during the build but because the
script return 0 travis thinks the build pass. How could we make it better ?

Is there docs somewhere about how to build this book?

Le jeu. 8 sept. 2016 à 09:44, Pieter Hintjens <notifications@github.com> a
écrit :

**Comment by hintjens** [comment]
I never really documented the process because it was a personal
toolchain... It's bin/mkbook iirc and need various things installed.

**Pull request merged**
